ALTER TABLE TD_GRUPOS_FAMILIARES ADD COLUMN dsParentesco1 VARCHAR(50) NULL AFTER dsTelefonoContacto;
ALTER TABLE TD_GRUPOS_FAMILIARES ADD COLUMN dsParentescoMail1 VARCHAR(50) NULL AFTER dsMailContacto;
ALTER TABLE TD_GRUPOS_FAMILIARES ADD COLUMN dsTelefonoContacto2 VARCHAR(50) NULL AFTER dsParentescoMail1;
ALTER TABLE TD_GRUPOS_FAMILIARES ADD COLUMN dsParentesco2 VARCHAR(50) NULL AFTER dsTelefonoContacto2;
ALTER TABLE TD_GRUPOS_FAMILIARES ADD COLUMN dsMailContacto2 VARCHAR(100) NULL AFTER dsParentesco2;
ALTER TABLE TD_GRUPOS_FAMILIARES ADD COLUMN dsParentescoMail2 VARCHAR(50) NULL AFTER dsMailContacto2;
